//! Emits the Arch package format: `.PKGINFO` first, then the package tree,
//! as a zstd-compressed tar. The archive is deterministic — sorted entries,
//! zeroed mtimes, root ownership — so rebuilding unchanged inputs yields
//! identical bytes, which is what lets a future repository dedupe by hash.

use std::io::Write as _;
use std::os::unix::fs::{MetadataExt as _, PermissionsExt as _};
use std::path::{Path, PathBuf};

use crate::error::{Error, Result};
use crate::pkgbuild::Pkgbuild;

pub fn package(pb: &Pkgbuild, pkgdir: &Path, out_dir: &Path) -> Result<PathBuf> {
    let mut entries = Vec::new();
    collect(pkgdir, pkgdir, &mut entries)?;
    if entries.iter().all(|(_, kind)| matches!(kind, Kind::Dir)) {
        // package() that produced nothing: refusing here is what keeps the
        // built table honest.
        return Err(Error::Build {
            stage: "package",
            log: pkgdir.parent().unwrap_or(pkgdir).join("build.log"),
        });
    }
    entries.sort_by(|(a, _), (b, _)| a.cmp(b));

    let name = pb.pkgname.first().cloned().unwrap_or_default();
    let full = pb.full_version();
    let size: u64 = entries
        .iter()
        .filter_map(|(_, kind)| match kind {
            Kind::File { size, .. } => Some(*size),
            _ => None,
        })
        .sum();

    let mut pkginfo = String::new();
    pkginfo.push_str("# Generated by qpkg\n");
    pkginfo.push_str(&format!("pkgname = {name}\n"));
    pkginfo.push_str(&format!("pkgver = {full}\n"));
    pkginfo.push_str("arch = x86_64\n");
    // Zero, deliberately: a real timestamp would make every rebuild a new
    // artifact.
    pkginfo.push_str("builddate = 0\n");
    pkginfo.push_str("packager = qpkg\n");
    pkginfo.push_str(&format!("size = {size}\n"));
    for dep in &pb.depends {
        pkginfo.push_str(&format!("depend = {dep}\n"));
    }

    std::fs::create_dir_all(out_dir)?;
    let out_path = out_dir.join(format!("{name}-{full}-x86_64.pkg.tar.zst"));
    let file = std::fs::File::create(&out_path)?;
    let encoder = zstd::stream::write::Encoder::new(file, 19)
        .map_err(|e| Error::Extraction(e.to_string()))?;
    let mut tar = tar::Builder::new(encoder);
    tar.mode(tar::HeaderMode::Deterministic);

    let mut header = base_header();
    header.set_entry_type(tar::EntryType::Regular);
    header.set_mode(0o644);
    header.set_size(pkginfo.len() as u64);
    header.set_cksum();
    tar.append_data(&mut header, ".PKGINFO", pkginfo.as_bytes())
        .map_err(|e| Error::Extraction(e.to_string()))?;

    for (rel, kind) in &entries {
        let mut header = base_header();
        match kind {
            Kind::Dir => {
                header.set_entry_type(tar::EntryType::Directory);
                header.set_mode(0o755);
                header.set_size(0);
                header.set_cksum();
                tar.append_data(&mut header, rel, std::io::empty())
                    .map_err(|e| Error::Extraction(e.to_string()))?;
            }
            Kind::File { mode, .. } => {
                let content = std::fs::read(pkgdir.join(rel))?;
                header.set_entry_type(tar::EntryType::Regular);
                header.set_mode(*mode);
                header.set_size(content.len() as u64);
                header.set_cksum();
                tar.append_data(&mut header, rel, content.as_slice())
                    .map_err(|e| Error::Extraction(e.to_string()))?;
            }
            Kind::Symlink { target } => {
                header.set_entry_type(tar::EntryType::Symlink);
                header.set_mode(0o777);
                header.set_size(0);
                tar.append_link(&mut header, rel, target)
                    .map_err(|e| Error::Extraction(e.to_string()))?;
            }
        }
    }
    let encoder = tar.into_inner().map_err(|e| Error::Extraction(e.to_string()))?;
    let mut file = encoder.finish().map_err(|e| Error::Extraction(e.to_string()))?;
    file.flush()?;
    Ok(out_path)
}

/// Root-owned, epoch-dated: the on-disk build ran as the invoking user, and
/// none of that identity belongs in the artifact.
fn base_header() -> tar::Header {
    let mut header = tar::Header::new_gnu();
    header.set_uid(0);
    header.set_gid(0);
    header.set_mtime(0);
    let _ = header.set_username("root");
    let _ = header.set_groupname("root");
    header
}

enum Kind {
    Dir,
    File { size: u64, mode: u32 },
    Symlink { target: PathBuf },
}

fn collect(pkgdir: &Path, dir: &Path, out: &mut Vec<(PathBuf, Kind)>) -> Result<()> {
    for entry in std::fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        let rel = path.strip_prefix(pkgdir).expect("walk stays under pkgdir").to_path_buf();
        let meta = std::fs::symlink_metadata(&path)?;
        if meta.file_type().is_symlink() {
            out.push((rel, Kind::Symlink { target: std::fs::read_link(&path)? }));
        } else if meta.is_dir() {
            out.push((rel, Kind::Dir));
            collect(pkgdir, &path, out)?;
        } else {
            let mode = meta.permissions().mode() & 0o7777;
            out.push((rel, Kind::File { size: meta.size(), mode }));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Read as _;
    use std::os::unix::fs::symlink;

    fn pb() -> Pkgbuild {
        Pkgbuild {
            pkgname: vec!["hello".into()],
            pkgver: "2.12".into(),
            pkgrel: "3".into(),
            epoch: Some("1".into()),
            depends: vec!["musl".into(), "zlib>=1.3".into()],
            ..Default::default()
        }
    }

    fn build_tree(dir: &Path) -> PathBuf {
        let pkgdir = dir.join("pkg");
        std::fs::create_dir_all(pkgdir.join("usr/bin")).unwrap();
        std::fs::write(pkgdir.join("usr/bin/hello"), "#!/bin/sh\necho hi\n").unwrap();
        std::fs::set_permissions(
            pkgdir.join("usr/bin/hello"),
            std::fs::Permissions::from_mode(0o755),
        )
        .unwrap();
        symlink("hello", pkgdir.join("usr/bin/hi")).unwrap();
        pkgdir
    }

    fn read_entries(archive_path: &Path) -> Vec<(String, u64, u64, String)> {
        let file = std::fs::File::open(archive_path).unwrap();
        let decoder = zstd::Decoder::new(file).unwrap();
        let mut archive = tar::Archive::new(decoder);
        archive
            .entries()
            .unwrap()
            .map(|e| {
                let mut e = e.unwrap();
                let mut content = String::new();
                if e.header().entry_type() == tar::EntryType::Regular {
                    e.read_to_string(&mut content).unwrap();
                }
                (
                    e.path().unwrap().display().to_string(),
                    e.header().uid().unwrap(),
                    e.header().gid().unwrap(),
                    content,
                )
            })
            .collect()
    }

    #[test]
    fn pkginfo_leads_and_the_tree_roundtrips_root_owned() {
        let dir = tempfile::tempdir().unwrap();
        let pkgdir = build_tree(dir.path());
        let out = package(&pb(), &pkgdir, &dir.path().join("artifacts")).unwrap();
        assert!(out.ends_with("hello-1:2.12-3-x86_64.pkg.tar.zst"), "{}", out.display());

        let entries = read_entries(&out);
        assert_eq!(entries[0].0, ".PKGINFO");
        let pkginfo = &entries[0].3;
        assert!(pkginfo.contains("pkgver = 1:2.12-3"), "{pkginfo}");
        assert!(pkginfo.contains("depend = zlib>=1.3"), "{pkginfo}");
        assert!(pkginfo.contains("size = 18"), "{pkginfo}");

        let hello = entries.iter().find(|(p, ..)| p == "usr/bin/hello").unwrap();
        assert_eq!(hello.3, "#!/bin/sh\necho hi\n");
        // Negative: the on-disk files belong to the test user, the archive
        // says root — ownership was normalized at write time.
        assert!(entries.iter().all(|(_, uid, gid, _)| (*uid, *gid) == (0, 0)));
    }

    #[test]
    fn identical_input_yields_identical_bytes() {
        let dir = tempfile::tempdir().unwrap();
        let pkgdir = build_tree(dir.path());
        let a = package(&pb(), &pkgdir, &dir.path().join("a")).unwrap();
        let b = package(&pb(), &pkgdir, &dir.path().join("b")).unwrap();
        assert_eq!(std::fs::read(a).unwrap(), std::fs::read(b).unwrap());
    }

    #[test]
    fn an_empty_package_tree_is_refused() {
        let dir = tempfile::tempdir().unwrap();
        let pkgdir = dir.path().join("pkg");
        // Directories alone do not make a package.
        std::fs::create_dir_all(pkgdir.join("usr/lib")).unwrap();
        let err = package(&pb(), &pkgdir, &dir.path().join("artifacts")).unwrap_err();
        match err {
            Error::Build { stage, .. } => assert_eq!(stage, "package"),
            other => panic!("expected Build, got {other:?}"),
        }
        // Negative: nothing was written.
        assert!(!dir.path().join("artifacts").exists());
    }
}
