[package]
name = "qunix-mm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]

[features]
default = []
std = []

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }

[[bench]]
name = "buddy"
harness = false

[[bench]]
name = "slab"
harness = false
