//! Asynchronous block I/O over virtio-blk.
//!
//! A request is a three-descriptor chain — header, data, status — published to
//! the one virtqueue and completed by an MSI-X interrupt, which unparks the
//! thread waiting in `task::block_on`.
//!
//! # Every device-visible address is one the kernel derived
//!
//! There is no IOMMU. The device addresses physical memory directly and will
//! write anywhere it is told to, so the only thing between a driver bug and an
//! arbitrary memory write is that every address published in a descriptor came
//! from a frame this module allocated.
//!
//! That is why a read lands in a kernel-owned bounce buffer and is copied to
//! the caller afterwards, rather than the caller's slice being published. A
//! caller's buffer can straddle frames, sit partly outside one, or — once
//! syscalls reach this path — be a user pointer. One place derives
//! device-visible addresses, and it derives them from frames it owns.

use core::future::Future;
use core::pin::Pin;
use core::sync::atomic::{AtomicU64, Ordering};
use core::task::{Context, Poll};

use qunix_hal_x86_64::pci;
use qunix_sched::ThreadId;
use qunix_sync::IrqSpinLock;
use qunix_virtio::blk::{BlkStatus, RequestHeader, SECTOR_BYTES, status_from_byte};
use qunix_virtio::{Descriptor, QUEUE_SIZE, RING_HEADER, SplitQueue, ring_layout};

use crate::virtio::{Transport, VIRTIO_BLK_MODERN, VIRTIO_F_VERSION_1};

/// The vector completions arrive on. 32 is the timer, 33 the TLB shootdown,
/// 34 the wake IPI.
pub const COMPLETION_VECTOR: u8 = 35;

/// Bytes of bounce buffer per in-flight request, and so the largest transfer.
///
/// One page. A larger request would need either a contiguous multi-page
/// allocation per slot — 64 of them — or a descriptor chain per page, and
/// neither is worth building before a filesystem exists to say what sizes it
/// actually asks for.
const SLOT_BYTES: usize = 4096;
/// The largest transfer, in sectors.
///
/// The bound `submit` actually applies, so a caller reading this and a caller
/// reading the code cannot disagree — it used to be stated here and enforced
/// against `SLOT_BYTES` separately.
pub const MAX_SECTORS: usize = SLOT_BYTES / SECTOR_BYTES;

/// Sectors on the attached disk.
///
/// Stated here and generated by `xtask::image::build_test_disk`; the two are
/// checked against each other by the device-error test, which asks for the
/// sector one past the end and requires the device to refuse it. If the image
/// grows and this does not, that test stops testing the error path and starts
/// testing a successful read — so it asserts the refusal rather than merely
/// calling the function.
const DISK_SECTORS: u64 = 2048;

/// Why a request could not be made.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BlockError {
    /// The buffer is not a whole number of sectors.
    ///
    /// Refused here rather than by the device: a partial sector makes the
    /// device write past the end of the buffer, and nothing between this
    /// function and the DMA engine would object.
    Unaligned,
    /// The buffer is larger than one slot's bounce buffer.
    TooLarge,
    /// Every descriptor is in flight.
    QueueFull,
    /// No virtio-blk device was found.
    NoDevice,
    /// The device was found but could not be brought up.
    ///
    /// Carries the cause. `ProbeError` distinguishes "no device", "the device
    /// is legacy", "it refused our features", "its queue is smaller than ours"
    /// and "a capability is malformed" precisely so that a failure names
    /// itself — collapsing all of them into one variant threw that away at the
    /// only place it was ever going to be read.
    Probe(crate::virtio::ProbeError),
    /// A DMA region could not be allocated.
    OutOfMemory,
    /// The device's capability list could not be walked.
    Capabilities(pci::CapError),
    /// The device declares no MSI-X capability, or one this driver cannot parse.
    NoMsix,
    /// The device's MSI-X table would fall outside the BAR that holds it.
    MsixOutsideBar,
    /// The device reported a failure for this request.
    Device(BlkStatus),
    /// The request was still outstanding at its deadline.
    ///
    /// The device never completed it: it may not have fetched the descriptor,
    /// the completion interrupt may not have been delivered, or the completion
    /// may have been refused. All of those are otherwise a thread parked
    /// forever, which reports nothing.
    Timeout,
}

/// One in-flight request.
#[derive(Debug, Clone, Copy)]
struct Slot {
    /// The thread to unpark when this completes.
    thread: ThreadId,
    /// Set by the interrupt handler.
    done: bool,
    /// The status byte the device wrote.
    status: u8,
    /// The submitter gave up waiting, but the device was never told.
    ///
    /// The chain stays allocated while this is set. A timeout means the driver
    /// stopped waiting, not that the device stopped owning the descriptors and
    /// the bounce buffer -- a merely slow completion still lands, and if the
    /// head has been recycled it lands on somebody else's request.
    abandoned: bool,
}

/// The device and everything that must be consistent with it, under one lock.
struct Blk {
    transport: Transport,
    queue: SplitQueue,
    /// Virtual address of the ring allocation, through the HHDM.
    ring_virt: u64,
    /// Physical base of the per-slot request areas (header, then status).
    meta_phys: u64,
    meta_virt: u64,
    /// Physical base of the per-slot bounce buffers.
    data_phys: u64,
    data_virt: u64,
    /// Used-ring entries already consumed.
    last_used: u16,
    slots: [Option<Slot>; QUEUE_SIZE as usize],
}

// SAFETY: `Blk` is reachable only through `DEVICE`, an `IrqSpinLock`, so every
// access is serialised. The raw addresses it holds name DMA memory and device
// registers, both of which are equally valid from any processor.
unsafe impl Send for Blk {}

static DEVICE: IrqSpinLock<Option<Blk>, qunix_hal_x86_64::Irq> = IrqSpinLock::new(None);

/// Completions taken from the used ring since boot.
///
/// Exposed so a test can require the *interrupt handler* to have run, rather
/// than inferring it from the request having finished — which a polling loop
/// would also satisfy.
static COMPLETIONS: AtomicU64 = AtomicU64::new(0);

pub fn completions() -> u64 {
    COMPLETIONS.load(Ordering::Acquire)
}

/// Completions the driver refused, or used indices it would not follow.
///
/// Every one of these strands a thread and leaks a descriptor chain, so the
/// harness requires it not to move. A device that misbehaves this way is not
/// something the driver can recover from silently, and "the machine hangs" is
/// not a diagnosis.
static DEVICE_FAULTS: AtomicU64 = AtomicU64::new(0);

/// Requests whose deadline expired, leaving their chain quarantined.
static ABANDONED: AtomicU64 = AtomicU64::new(0);

/// Quarantined chains the device later completed, and which were then freed.
///
/// The gap between this and [`ABANDONED`] is chains leaked for good: the device
/// never handed them back, so the driver may never reuse them.
static RECLAIMED: AtomicU64 = AtomicU64::new(0);

pub fn abandoned() -> u64 {
    ABANDONED.load(Ordering::Acquire)
}

pub fn reclaimed() -> u64 {
    RECLAIMED.load(Ordering::Acquire)
}

pub fn device_faults() -> u64 {
    DEVICE_FAULTS.load(Ordering::Acquire)
}

/// Polls that found a request still outstanding — i.e. that parked.
///
/// Exposed so a test can require the *asynchronous* path to have run. A
/// completion that lands before the first poll makes the future `Ready`
/// immediately, and the park/unpark path this milestone exists for never
/// executes — while every assertion about the data still holds.
static PENDING_POLLS: AtomicU64 = AtomicU64::new(0);

pub fn pending_polls() -> u64 {
    PENDING_POLLS.load(Ordering::Acquire)
}

/// Bytes of metadata per slot.
///
/// A 16-byte header and a 1-byte status is 17; the stride is 32 so that every
/// slot's header is 32-byte aligned and no two slots share a cache line, which
/// keeps a completion's status write from invalidating a neighbour's header
/// while the device is reading it.
///
/// 64 slots at this stride is 2048 bytes — half the frame `init` allocates for
/// them. The `const` assertion below is what keeps that true: the comment
/// claiming "one page" was simply wrong arithmetic, and a claim about a bound
/// is worth nothing if raising `QUEUE_SIZE` does not break it.
const META_STRIDE: u64 = 32;

const _: () = assert!(
    META_STRIDE as usize * QUEUE_SIZE as usize <= 4096,
    "the per-slot metadata no longer fits the single frame `init` allocates"
);
const _: () = assert!(
    META_STRIDE >= RequestHeader::BYTES as u64 + 1,
    "a slot's status byte overlaps the next slot's header"
);

/// Frames held only until `init` succeeds.
///
/// A `Drop` guard rather than a cleanup arm on each `?`, because there are six
/// fallible steps after the first allocation and an early return from any of
/// them would otherwise leak everything taken so far.
#[derive(Default)]
struct FrameGuard {
    held: [Option<(u64, u8)>; 3],
    used: usize,
}

impl FrameGuard {
    fn take(&mut self, order: u8) -> Option<u64> {
        let phys = crate::frames::alloc(order)?;
        self.held[self.used] = Some((phys, order));
        self.used += 1;
        Some(phys)
    }

    /// Hands ownership to the caller; nothing is freed on drop.
    fn keep(&mut self) {
        self.used = 0;
        self.held = [None; 3];
    }
}

impl Drop for FrameGuard {
    fn drop(&mut self) {
        for slot in self.held.iter().flatten() {
            // SAFETY: each frame came from `frames::alloc` in `take` and, since
            // `keep` was not called, was never handed to the device or to any
            // other owner.
            unsafe { crate::frames::free(slot.0, slot.1) };
        }
    }
}

/// Brings up the block device. Idempotent.
///
/// # Safety
/// Must be called from the bootstrap processor with interrupts enabled and the
/// LAPIC mapped, before any request is submitted.
pub unsafe fn init() -> Result<(), BlockError> {
    let mut guard = DEVICE.lock();
    if guard.is_some() {
        return Ok(());
    }

    // SAFETY: the caller's obligation, forwarded.
    let mut transport = unsafe { crate::virtio::probe(VIRTIO_BLK_MODERN) }
        .map_err(BlockError::Probe)?;
    transport.negotiate(VIRTIO_F_VERSION_1).map_err(BlockError::Probe)?;

    let layout = ring_layout(QUEUE_SIZE);
    // Every frame is released again on any later failure. `init` is documented
    // idempotent and a caller may retry it, and each failed attempt otherwise
    // strands 66 pages with nothing able to reclaim them. A guard, because `?`
    // has no cleanup clause and this kernel does not unwind.
    let mut frames = FrameGuard::default();
    let ring_phys = frames.take(0).ok_or(BlockError::OutOfMemory)?;
    // 64 slots at META_STRIDE, which a const assertion pins inside one frame.
    let meta_phys = frames.take(0).ok_or(BlockError::OutOfMemory)?;
    // 64 slots of 4 KiB is 256 KiB: order 6.
    let data_phys = frames.take(6).ok_or(BlockError::OutOfMemory)?;
    let hhdm = crate::boot::hhdm_offset();

    // Zeroed before the device is told about any of it. The device reads the
    // available ring's index the moment the queue is enabled, and a frame
    // carrying whatever its last owner left would have it fetch descriptors
    // that were never written -- from addresses that were never derived.
    // SAFETY: the frames were just allocated, so nothing else refers to them,
    // and the HHDM maps all of RAM.
    unsafe {
        core::ptr::write_bytes((hhdm + ring_phys) as *mut u8, 0, 4096);
        core::ptr::write_bytes((hhdm + meta_phys) as *mut u8, 0, 4096);
        core::ptr::write_bytes((hhdm + data_phys) as *mut u8, 0, SLOT_BYTES * QUEUE_SIZE as usize);
    }

    // Configure, bind the interrupt, *then* enable. The specification requires
    // every queue field to be set before `queue_enable`, and a device may latch
    // them there -- so binding MSI-X afterwards works under QEMU and sends
    // completions nowhere on a device that latches.
    transport.configure_queue(layout, ring_phys).map_err(BlockError::Probe)?;
    // SAFETY: the caller guarantees the LAPIC is mapped and this runs on the
    // bootstrap processor.
    unsafe { install_msix(&mut transport)? };
    transport.enable_queue();
    transport.finish().map_err(BlockError::Probe)?;

    // Committed: from here the frames belong to the driver, not the guard.
    frames.keep();
    *guard = Some(Blk {
        transport,
        queue: SplitQueue::new(QUEUE_SIZE),
        ring_virt: hhdm + ring_phys,
        meta_phys,
        meta_virt: hhdm + meta_phys,
        data_phys,
        data_virt: hhdm + data_phys,
        last_used: 0,
        slots: [None; QUEUE_SIZE as usize],
    });
    Ok(())
}

/// Programs the device's MSI-X table entry 0 to deliver to
/// [`COMPLETION_VECTOR`], and points the queue at it.
///
/// # Safety
/// The LAPIC must be mapped and this CPU's IDT must already carry the vector.
unsafe fn install_msix(transport: &mut Transport) -> Result<(), BlockError> {
    let bdf = transport.bdf();
    // SAFETY: port I/O from ring 0.
    let cfg = unsafe { pci::config_snapshot(bdf) };
    let caps = pci::walk_capabilities(&cfg).map_err(BlockError::Capabilities)?;
    let cap = caps.iter().find(|c| c.id == pci::CAP_ID_MSIX).ok_or(BlockError::NoMsix)?;
    let msix = pci::parse_msix(&cfg, *cap).ok_or(BlockError::NoMsix)?;

    // SAFETY: port I/O.
    let (bar, bar_size) =
        unsafe { transport.bar_base(msix.bar) }.ok_or(BlockError::MsixOutsideBar)?;
    let table_bytes = (msix.entries as u32).saturating_mul(pci::MSIX_ENTRY_BYTES as u32);
    // The table must lie inside its BAR. `msix.offset` and `msix.entries` are
    // both device-supplied, and `MsixTable::program` writes four dwords per
    // entry -- so without this the device chooses where those writes land.
    let end = (msix.offset as u64).saturating_add(table_bytes as u64);
    if end > bar_size {
        return Err(BlockError::MsixOutsideBar);
    }
    let table_phys = bar + msix.offset as u64;
    let table_virt = crate::virtio::map_device_window(table_phys, table_bytes)
        .ok_or(BlockError::OutOfMemory)?;

    // SAFETY: `table_virt` was just mapped uncacheable, and its length was
    // checked against the BAR that holds it, for `msix.entries` entries.
    let table = unsafe { pci::MsixTable::new(table_virt, msix.entries) };
    let address = pci::msix_message_address(
        qunix_hal_x86_64::apic::phys_base(),
        // Delivered to the bootstrap processor. Any processor would do -- the
        // handler unparks a thread the scheduler may then run anywhere -- but
        // naming one keeps the destination a fact rather than a race.
        0,
    );
    // SAFETY: the table was just mapped uncacheable with `entries` entries.
    unsafe { table.program(0, address, pci::msix_message_data(COMPLETION_VECTOR)) }
        .map_err(|_| BlockError::NoMsix)?;

    // Enable MSI-X, and clear the function mask. Enabling without clearing the
    // mask is the shape of mistake that produces a device which accepts every
    // request and never interrupts.
    // SAFETY: port I/O.
    unsafe {
        let control_dword = msix.control_offset & !0b11;
        let raw = pci::config_read32(bdf, control_dword);
        let shift = (msix.control_offset & 0b11) * 8;
        let control = ((raw >> shift) as u16) | pci::MSIX_CONTROL_ENABLE;
        let control = control & !pci::MSIX_CONTROL_FUNCTION_MASK;
        let cleared = raw & !(0xffffu32 << shift);
        pci::config_write32(bdf, control_dword, cleared | ((control as u32) << shift));
    }

    transport.set_queue_msix_vector(0);
    Ok(())
}

/// A submitted request, quarantined if the caller never waits for it.
///
/// `read_at`/`write_at` `await` a completion, and a future may be dropped
/// before it resolves -- a thread torn down mid-`block_on`, or the request
/// composed into a timeout. The chain is *not* freed on that path, for the
/// same reason the deadline does not free it: the device may still be reading
/// those descriptors and writing that bounce buffer, so handing them to the
/// next request lets a late completion mark somebody else's request done from
/// a status byte written for this one.
///
/// So it is quarantined exactly as a timeout is, and `handle_completion`
/// reclaims it when the completion arrives. Without this the chain is neither
/// freed nor quarantined: one of 21 in-flight slots is consumed per abandoned
/// request, and the queue drains into `QueueFull` errors in code with nothing
/// to do with the cause.
struct Request {
    head: u16,
    /// Set once `finish` has taken responsibility for the chain.
    settled: bool,
}

impl Drop for Request {
    fn drop(&mut self) {
        if self.settled {
            return;
        }
        let mut guard = DEVICE.lock();
        let Some(blk) = guard.as_mut() else { return };
        if let Some(slot) = blk.slots[self.head as usize].as_mut() {
            slot.abandoned = true;
        }
        ABANDONED.fetch_add(1, Ordering::AcqRel);
    }
}

/// Reads `buf.len()` bytes starting at sector `lba`.
pub async fn read_at(lba: u64, buf: &mut [u8]) -> Result<(), BlockError> {
    // The deadline first. See `reserve_deadline`: once `submit` returns, the
    // device owns the chain, and there is no correct way to take it back.
    let deadline = reserve_deadline()?;
    let head = submit(lba, buf.len(), None)?;
    let mut request = Request { head, settled: false };
    let status = Completion { head, deadline }.await;
    // From here the chain is `finish`'s responsibility, not the guard's.
    request.settled = true;
    finish(head, status, Some(buf))
}

/// Writes `buf` starting at sector `lba`.
pub async fn write_at(lba: u64, buf: &[u8]) -> Result<(), BlockError> {
    let deadline = reserve_deadline()?;
    let head = submit(lba, buf.len(), Some(buf))?;
    let mut request = Request { head, settled: false };
    let status = Completion { head, deadline }.await;
    // From here the chain is `finish`'s responsibility, not the guard's.
    request.settled = true;
    finish(head, status, None)
}

/// A timer that fires if the request is still outstanding at the deadline.
///
/// Taken **before** the request is published, and that order is the whole
/// point. Reserving it afterwards meant a full timer table had to undo a chain
/// the device already owned -- `submit` publishes the available ring and
/// notifies before returning -- so the driver freed descriptors and a bounce
/// buffer while the device was reading them, and the next request reused the
/// same head and the same physical addresses. The device then wrote one
/// request's data into another's buffer, and every operation returned success.
///
/// Reserving first cannot fail that way: nothing has been published yet, and a
/// `Sleep` dropped on the way out releases its slot.
fn reserve_deadline() -> Result<crate::task::Sleep, BlockError> {
    crate::task::try_sleep_ticks(REQUEST_TIMEOUT_TICKS).map_err(|_| BlockError::QueueFull)
}

/// Validates, builds and publishes a request chain. Returns its head.
fn submit(lba: u64, len: usize, out: Option<&[u8]>) -> Result<u16, BlockError> {
    if len == 0 || len % SECTOR_BYTES != 0 {
        return Err(BlockError::Unaligned);
    }
    if len > MAX_SECTORS * SECTOR_BYTES {
        return Err(BlockError::TooLarge);
    }

    let mut guard = DEVICE.lock();
    let blk = guard.as_mut().ok_or(BlockError::NoDevice)?;

    let head = blk.queue.alloc_chain(3).ok_or(BlockError::QueueFull)?;
    let data = blk.queue.next_in_chain(head).expect("a three-chain has a second descriptor");
    let status = blk.queue.next_in_chain(data).expect("a three-chain has a third descriptor");

    // The slot index is the *head descriptor*, so the metadata and bounce
    // buffer belong to this request for as long as the chain does. Indexing by
    // anything else -- a rotating counter, say -- would let two in-flight
    // requests share a bounce buffer, and the device would fill both with one
    // sector's contents.
    let slot = head as u64;
    let header_phys = blk.meta_phys + slot * META_STRIDE;
    let status_phys = header_phys + RequestHeader::BYTES as u64;
    let data_phys = blk.data_phys + slot * SLOT_BYTES as u64;
    let header_virt = blk.meta_virt + slot * META_STRIDE;
    let data_virt = blk.data_virt + slot * SLOT_BYTES as u64;

    let request =
        if out.is_some() { RequestHeader::write(lba) } else { RequestHeader::read(lba) };
    // SAFETY: `header_virt` is inside the metadata frame this module allocated
    // and mapped through the HHDM.
    unsafe {
        core::ptr::copy_nonoverlapping(
            request.to_bytes().as_ptr(),
            header_virt as *mut u8,
            RequestHeader::BYTES,
        );
        // The status byte must not carry a stale success from the previous use
        // of this slot: the device writes it, but a request that never reaches
        // the device would otherwise read as `Ok`.
        //
        // Unfalsifiable here, and said so: every request in this suite does
        // reach the device, which overwrites the byte, so removing this line
        // leaves the tests green. It guards the case where a request is
        // published and the device never fetches it -- a lost notification, a
        // ring the device rejected -- where the difference is between reporting
        // an error and reporting success on data that was never transferred.
        core::ptr::write_volatile((header_virt + RequestHeader::BYTES as u64) as *mut u8, 0xff);
    }
    if let Some(bytes) = out {
        // SAFETY: the bounce buffer is `SLOT_BYTES` and `len` was bounded by it.
        unsafe { core::ptr::copy_nonoverlapping(bytes.as_ptr(), data_virt as *mut u8, len) };
    }

    blk.queue.describe(head, header_phys, RequestHeader::BYTES as u32, false);
    // Device-writable exactly when the device is the one producing the data.
    // Marking a read's buffer read-only makes the device refuse the chain,
    // which at least fails loudly; marking a write's buffer device-writable
    // hands it a page it may overwrite with nothing in particular.
    blk.queue.describe(data, data_phys, len as u32, out.is_none());
    blk.queue.describe(status, status_phys, 1, true);

    blk.slots[head as usize] =
        Some(Slot { thread: crate::sched::current_id(), done: false, status: 0xff, abandoned: false });

    blk.queue.publish(head);
    write_rings(blk, head);
    blk.transport.notify();
    Ok(head)
}

/// Copies the chain `head` names, and the ring slot naming it, into DMA memory.
///
/// Only that chain and only that slot. Writing the whole table -- 64
/// descriptors and 64 ring slots, serialised into two heap allocations -- is
/// what this did on every submission, under the device lock with interrupts
/// masked, to publish three descriptors and one slot. It also rewrote entries
/// belonging to requests already in flight, with the same bytes, which is
/// pointless work the device is entitled to be reading through.
fn write_rings(blk: &Blk, head: u16) {
    let layout = ring_layout(QUEUE_SIZE);
    // The chain's descriptors and its ring slot first, *without* the index.
    let mut next = Some(head);
    while let Some(index) = next {
        let bytes = blk
            .queue
            .descriptor_bytes(index)
            .expect("a chain names a descriptor outside the table");
        // SAFETY: the offset is inside the ring frame this module allocated,
        // and `ring_layout` is what told the device where the table is.
        unsafe {
            core::ptr::copy_nonoverlapping(
                bytes.as_ptr(),
                (blk.ring_virt + layout.desc as u64 + index as u64 * Descriptor::BYTES as u64)
                    as *mut u8,
                bytes.len(),
            );
        }
        next = blk.queue.next_in_chain(index);
    }
    // The slot `publish` just filled: the ring position, which is the
    // free-running index reduced modulo the queue size. Using the index itself
    // writes outside the ring the moment it passes `QUEUE_SIZE`.
    let slot = blk.queue.avail_index().wrapping_sub(1) % QUEUE_SIZE;
    let slot_bytes = blk.queue.avail_slot_bytes(slot).expect("the published slot is off the ring");
    // SAFETY: as above; `slot` is below `QUEUE_SIZE` by construction.
    unsafe {
        core::ptr::copy_nonoverlapping(
            slot_bytes.as_ptr(),
            (blk.ring_virt
                + layout.avail as u64
                + SplitQueue::AVAIL_SLOTS_OFFSET as u64
                + slot as u64 * 2) as *mut u8,
            slot_bytes.len(),
        );
    }
    // Then the barrier, then the index. This order is the protocol, not
    // caution: the index is what makes the slot valid, so a device permitted to
    // poll the ring can otherwise observe an incremented index over a slot
    // still holding its previous occupant -- a head that `finish` has since
    // freed -- and fetch a descriptor for a request nobody made. Publishing
    // both in one copy, as this did, cannot express the ordering at all.
    core::sync::atomic::fence(Ordering::Release);
    // SAFETY: inside the ring frame, at the offset `ring_layout` reserved.
    unsafe {
        core::ptr::write_volatile(
            (blk.ring_virt + layout.avail as u64 + SplitQueue::AVAIL_IDX_OFFSET as u64) as *mut u16,
            blk.queue.avail_index(),
        );
    }
    // And a full fence before the notification, which is a store to a device
    // register: without it the two stores can reach memory in the other order
    // and the device reads a ring that does not yet describe the request it was
    // told about.
    core::sync::atomic::fence(Ordering::SeqCst);
}

/// How long a request may be outstanding before the driver gives up on it.
///
/// At roughly 10 ms a tick this is about five seconds. A virtio-blk read that
/// has not completed by then is not slow, it is lost — and the alternative is
/// the failure this kernel is worst at reporting: a thread parked forever on a
/// completion that cannot arrive, surfacing as a harness timeout that names no
/// test and no cause.
const REQUEST_TIMEOUT_TICKS: u64 = 500;

/// The status byte value used to report a request the device never completed.
///
/// Distinct from every value the specification defines, so it decodes as
/// `BlkStatus::Unknown` rather than colliding with a real verdict.
const STATUS_TIMED_OUT: u8 = 0xfe;

/// A request's completion, or the deadline by which it must arrive.
///
/// The timer half is not decoration. Nothing else bounds the wait: the device
/// may never fetch the descriptor, the interrupt may be masked or misrouted, a
/// completion may be refused — and every one of those leaves the thread parked
/// with nothing able to wake it. Reusing T3's timer wheel means the deadline
/// *also* unparks the thread, so the future is polled again and can report the
/// failure rather than the machine simply stopping.
struct Completion {
    head: u16,
    deadline: crate::task::Sleep,
}

impl Future for Completion {
    type Output = u8;

    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<u8> {
        // The device first: a completion that arrives in the same tick as the
        // deadline is a completion, not a timeout.
        let this = unsafe { self.get_unchecked_mut() };
        if let Poll::Ready(status) = Self::poll_device(this.head) {
            return Poll::Ready(status);
        }
        if Pin::new(&mut this.deadline).poll(cx).is_ready() {
            return Poll::Ready(STATUS_TIMED_OUT);
        }
        Poll::Pending
    }
}

impl Completion {
    fn poll_device(head: u16) -> Poll<u8> {
        let guard = DEVICE.lock();
        let Some(blk) = guard.as_ref() else { return Poll::Ready(0xff) };
        match blk.slots[head as usize] {
            Some(slot) if slot.done => Poll::Ready(slot.status),
            // The waker is deliberately unused: `handle_completion` unparks the
            // thread recorded in the slot, which is the same thread this future
            // is being polled on and the same thing the waker would do. That is
            // only true because the thread *is* the task -- see `task`'s module
            // documentation.
            _ => {
                PENDING_POLLS.fetch_add(1, Ordering::AcqRel);
                Poll::Pending
            }
        }
    }
}

/// Copies the result out, releases the chain, and reports the device's verdict.
fn finish(head: u16, status: u8, into: Option<&mut [u8]>) -> Result<(), BlockError> {
    let mut guard = DEVICE.lock();
    let blk = guard.as_mut().ok_or(BlockError::NoDevice)?;
    if status == STATUS_TIMED_OUT {
        // Quarantined, not freed. The deadline expiring says the driver gave
        // up; it says nothing about the device, which may still be reading the
        // descriptors and writing the bounce buffer. Freeing the chain here
        // hands both to the next request, and a late completion then marks that
        // request done from a status byte written for this one -- a wrong
        // answer reported as success, which is the failure this driver is
        // arranged to prevent.
        //
        // The chain is reclaimed by `handle_completion` if the completion ever
        // arrives, and leaked if it never does. A permanently leaked chain
        // costs one of 21 in-flight slots and is visible in `free_count`; the
        // alternative costs correctness.
        if let Some(slot) = blk.slots[head as usize].as_mut() {
            slot.abandoned = true;
        }
        ABANDONED.fetch_add(1, Ordering::AcqRel);
        return Err(BlockError::Timeout);
    }
    if let Some(buf) = into {
        let data_virt = blk.data_virt + head as u64 * SLOT_BYTES as u64;
        // SAFETY: the bounce buffer is `SLOT_BYTES` and `buf.len()` was bounded
        // by it at submission.
        unsafe { core::ptr::copy_nonoverlapping(data_virt as *const u8, buf.as_mut_ptr(), buf.len()) };
    }
    blk.queue.free_chain(head);
    blk.slots[head as usize] = None;
    match status_from_byte(status) {
        BlkStatus::Ok => Ok(()),
        other => Err(BlockError::Device(other)),
    }
}

/// Drains the used ring and wakes whoever was waiting.
///
/// Runs in interrupt context. Everything it touches is behind `IrqSpinLock`, so
/// a tick cannot land on a processor already holding it.
pub fn handle_completion() {
    let mut woken: [Option<ThreadId>; QUEUE_SIZE as usize] = [None; QUEUE_SIZE as usize];
    let mut count = 0;
    {
        let mut guard = DEVICE.lock();
        let Some(blk) = guard.as_mut() else { return };
        let layout = ring_layout(QUEUE_SIZE);
        let used_len = layout.bytes - layout.used;
        let used_base = blk.ring_virt + layout.used as u64;

        // The device writes this memory while the driver reads it, so both the
        // ordering and the aliasing matter.
        //
        // `used.idx` is loaded first and *volatilely*, then an acquire fence,
        // then the entries. That order is the protocol: the index is what makes
        // the entries below it valid. Reading them from one `&[u8]` -- which is
        // what this did -- both tells the compiler the bytes cannot change,
        // which is false, and leaves it free to schedule the entry loads first.
        // A stale entry whose head has since been recycled by `finish` passes
        // `take_used`'s liveness check, and the driver then reads a status byte
        // the device has not written and copies a bounce buffer it is still
        // filling. Wrong data, reported as success.
        // SAFETY: the used ring is inside the frame this module allocated and
        // told the device about; `used_len` is what `ring_layout` reserved.
        let device_idx = unsafe { core::ptr::read_volatile((used_base + 2) as *const u16) };
        core::sync::atomic::fence(Ordering::Acquire);

        // The device chose `device_idx`, so the distance it claims to have
        // advanced is device-supplied too. More than the ring holds means the
        // device is lying: consuming that many entries would walk the mirror
        // repeatedly, and every pass can mark a *live* request done from a
        // status byte the device never wrote.
        let pending = device_idx.wrapping_sub(blk.last_used);
        if pending > QUEUE_SIZE {
            DEVICE_FAULTS.fetch_add(1, Ordering::AcqRel);
            return;
        }
        // Consumed in order from the last index seen. Reading only the newest
        // entry would drop every completion that arrived while this handler was
        // between the read and the lock.
        //
        // Each entry is copied out immediately before it is taken, and only the
        // entries the index says are ready. Copying the whole ring first --
        // which this did -- re-read all 64 slots on every interrupt for a
        // `pending` that is almost always 1, and those reads cover the slots
        // the device may be filling *right now*: bytes with no acquire
        // relationship to anything, kept in a mirror until some later
        // interrupt's index happens to reach them.
        for _ in 0..pending {
            let slot = blk.last_used % QUEUE_SIZE;
            let mut entry = [0u8; 8];
            // The bound the `SAFETY` note below rests on, checked rather than
            // asserted in prose: `used_len` is what `ring_layout` reserved, and
            // an entry that reached past it would be a read into whatever
            // follows the ring.
            debug_assert!(
                RING_HEADER + (slot as usize + 1) * 8 <= used_len,
                "used-ring entry {slot} lies outside the {used_len}-byte ring"
            );
            let entry_base = used_base + RING_HEADER as u64 + slot as u64 * 8;
            for (i, byte) in entry.iter_mut().enumerate() {
                // SAFETY: `slot` is below `QUEUE_SIZE`, so this is inside the
                // used ring established above -- `used_len` covers the header,
                // every entry, and the footer.
                *byte = unsafe { core::ptr::read_volatile((entry_base + i as u64) as *const u8) };
            }
            if !blk.queue.ingest_used_slot(slot, entry) {
                DEVICE_FAULTS.fetch_add(1, Ordering::AcqRel);
                return;
            }
            if let Some((head, _len)) = blk.queue.take_used(slot) {
                let status_virt =
                    blk.meta_virt + head as u64 * META_STRIDE + RequestHeader::BYTES as u64;
                // SAFETY: inside the metadata frame this module allocated.
                let status = unsafe { core::ptr::read_volatile(status_virt as *const u8) };
                if let Some(entry) = blk.slots[head as usize].as_mut() {
                    if entry.abandoned {
                        // The submitter timed out and left the chain behind for
                        // exactly this moment. Nothing to wake -- it took its
                        // error long ago -- and the descriptors are safe to
                        // reclaim now that the device has handed them back.
                        blk.queue.free_chain(head);
                        blk.slots[head as usize] = None;
                        RECLAIMED.fetch_add(1, Ordering::AcqRel);
                    } else {
                        entry.done = true;
                        entry.status = status;
                        woken[count] = Some(entry.thread);
                        count += 1;
                    }
                }
                COMPLETIONS.fetch_add(1, Ordering::AcqRel);
            } else {
                // A completion the driver refused: an id past the ring, or one
                // naming a descriptor that was never submitted. Counted rather
                // than dropped in silence, because dropping it strands the
                // thread that submitted the chain -- it is never marked done,
                // so it parks forever -- and leaks the chain, since `free_chain`
                // only runs from `finish`. Both are invisible without this.
                DEVICE_FAULTS.fetch_add(1, Ordering::AcqRel);
            }
            blk.last_used = blk.last_used.wrapping_add(1);
        }
    }
    // Unparked after the device lock is released: `unpark` takes the scheduler
    // lock and may take a run queue, and holding three from an interrupt is an
    // order nothing else in the kernel has.
    for id in woken.iter().flatten() {
        crate::sched::unpark(*id);
    }
}

/// Forgets the configured device.
///
/// The virtio transport tests call `probe`, which *resets* the device — and one
/// of them re-points queue 0 at a different ring and drives it back to
/// `DRIVER_OK` without re-binding MSI-X. This driver's `Blk` still describes
/// the ring the device has forgotten, and `init` is idempotent, so it would
/// never re-establish it: the next request would park forever on a queue the
/// device does not read.
///
/// Today that is green only because `mod block;` precedes `mod virtio;` and the
/// block tests therefore run first — an accident of two lines, written down
/// nowhere. Calling this makes the dependency a fact rather than an ordering.
#[cfg(test)]
pub fn invalidate_for_test() {
    *DEVICE.lock() = None;
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::task::block_on;

    fn ready() {
        // SAFETY: the suite runs on the bootstrap processor with the LAPIC
        // mapped and the vector installed.
        unsafe { init() }.expect("the block device did not come up");
    }

    /// Runs `body` and requires it not to have needed the request deadline.
    ///
    /// Every `block_on` here parks on a completion only the MSI-X handler can
    /// deliver, and the request timeout is what stops that being a harness
    /// timeout naming no test. But a timeout is still a *failure* of the thing
    /// under test, and one that returns `Err(Timeout)` from deep inside a
    /// helper reads as "the read failed" rather than as "no completion ever
    /// arrived". Requiring the fault counters to stay put says which.
    fn without_device_faults(what: &str, body: impl FnOnce()) {
        let faults = device_faults();
        body();
        assert_eq!(
            device_faults(),
            faults,
            "{what}: the driver refused {} completion(s); each strands a thread and leaks a \
             descriptor chain",
            device_faults() - faults
        );
    }

    #[test_case]
    fn a_sector_reads_back_the_lba_it_was_written_with() {
        // The disk is generated with each sector beginning with its own LBA, so
        // reading the *wrong* sector is detectable rather than plausible. A
        // test that only checked "the bytes are not zero" would pass on an
        // off-by-one anywhere in the descriptor chain.
        ready();
        let mut buf = [0u8; SECTOR_BYTES];
        without_device_faults("reading sector 7", || {
            block_on(read_at(7, &mut buf)).expect("the read failed");
        });
        assert_eq!(
            u64::from_le_bytes(buf[0..8].try_into().unwrap()),
            7,
            "sector 7 does not identify itself; the request named the wrong sector"
        );
        // And the tail, which also depends on the LBA -- a read that returned
        // the right first eight bytes and the wrong rest would otherwise pass.
        assert_eq!(buf[8], 7, "the sector's filler does not match its LBA");
        assert_eq!(buf[9], 8, "the filler is not the LBA plus its offset");
    }

    #[test_case]
    fn a_read_completes_from_the_interrupt_handler() {
        // The claim the milestone is about. `block_on` parks, and only the
        // MSI-X handler can make the thread runnable again -- so the completion
        // counter must move. Without it the request would have to have been
        // finished by something else, which is the polling loop this design
        // exists to avoid.
        ready();
        let before = completions();
        let polls_before = pending_polls();
        let mut buf = [0u8; SECTOR_BYTES];
        block_on(read_at(3, &mut buf)).expect("the read failed");
        // Exactly one, not "more than before". A handler that counted twice per
        // entry, or re-drained an already-consumed slot, satisfies a `>`.
        assert_eq!(
            completions(),
            before + 1,
            "the handler took {} used-ring entries for one request",
            completions() - before
        );
        // And the request must actually have *parked*. If the completion lands
        // before the first poll the future is Ready immediately, the
        // park/unpark path this milestone exists for never runs, and every
        // other assertion here still holds -- a green result would then say
        // only that the device is fast on this host, which CLAUDE.md rules out
        // as coverage.
        assert!(
            pending_polls() > polls_before,
            "the request was already complete at its first poll; the asynchronous path did \
             not run"
        );
        assert_eq!(u64::from_le_bytes(buf[0..8].try_into().unwrap()), 3);
    }

    /// A sector no read test touches, reserved for the write test.
    ///
    /// Above every LBA the read tests use, so a write cannot make one of them
    /// pass or fail for the wrong reason.
    const SCRATCH_SECTOR: u64 = 11;

    #[test_case]
    fn a_write_is_visible_to_a_later_read() {
        // The payload is derived from what is on the sector *now*, and that is
        // the whole test.
        //
        // The disk persists across boots and across runs -- deliberately, so a
        // write survives to be read back -- and the previous version of this
        // test wrote a fixed payload. From the second boot onward, including
        // the second boot of a single `cargo xtask test`, the sector already
        // held exactly that payload before the write. `write_at` could have
        // been deleted, or have written the wrong sector, or have flipped
        // REQUEST_OUT to REQUEST_IN, and the read-back would still have
        // matched. The only test of the write path could not fail.
        //
        // Inverting the current contents makes the payload different on every
        // run by construction.
        ready();
        let mut prior = [0u8; SECTOR_BYTES];
        block_on(read_at(SCRATCH_SECTOR, &mut prior)).expect("the prior read failed");
        let mut out = [0u8; SECTOR_BYTES];
        for (i, b) in out.iter_mut().enumerate() {
            *b = !prior[i];
        }
        assert_ne!(
            out, prior,
            "the payload equals what is already on the sector; this test cannot fail"
        );

        without_device_faults("writing the scratch sector", || {
            block_on(write_at(SCRATCH_SECTOR, &out)).expect("the write failed");
        });
        let mut back = [0u8; SECTOR_BYTES];
        block_on(read_at(SCRATCH_SECTOR, &mut back)).expect("the read failed");
        assert_eq!(back, out, "what came back is not what went out");
        assert_ne!(back, prior, "the sector still holds what it held before the write");
    }

    #[test_case]
    fn a_misaligned_or_oversized_request_is_refused_before_it_reaches_the_device() {
        // Refused in the driver, not by the device. A buffer that is not a
        // whole number of sectors makes the device write past its end -- and it
        // will, because nothing between here and the DMA engine checks.
        ready();
        // On the heap, not the stack. Between them these buffers are 8.7 KiB in
        // one frame -- more than any other test here -- and Limine's stack has
        // no guard page, so overrunning it corrupts whatever lies below instead
        // of faulting. A kernel test that needs kilobytes of buffer asks the
        // allocator for them.
        let mut short = alloc::vec![0u8; SECTOR_BYTES - 1];
        assert_eq!(block_on(read_at(0, &mut short)), Err(BlockError::Unaligned));
        let mut empty = [0u8; 0];
        assert_eq!(block_on(read_at(0, &mut empty)), Err(BlockError::Unaligned));
        assert_eq!(MAX_SECTORS * SECTOR_BYTES, SLOT_BYTES, "MAX_SECTORS does not describe the bound");
        let mut huge = alloc::vec![0u8; SLOT_BYTES + SECTOR_BYTES];
        assert_eq!(block_on(read_at(0, &mut huge)), Err(BlockError::TooLarge));
        // The largest legal transfer is accepted, so the bound cannot drift
        // downward and refuse a request it should carry.
        let mut biggest = alloc::vec![0u8; SLOT_BYTES];
        block_on(read_at(0, &mut biggest)).expect("the largest legal read was refused");
        assert_eq!(u64::from_le_bytes(biggest[0..8].try_into().unwrap()), 0);
        assert_eq!(
            u64::from_le_bytes(biggest[SECTOR_BYTES..SECTOR_BYTES + 8].try_into().unwrap()),
            1,
            "a multi-sector read did not advance the LBA across sectors"
        );
    }

    #[test_case]
    fn a_request_refused_for_want_of_a_timer_is_never_shown_to_the_device() {
        // The deadline is reserved before the chain is published, and this is
        // what that ordering buys. Reserving it afterwards left the only
        // failure path having to retract a request the device already owned:
        // `submit` publishes the available ring and notifies before it
        // returns, so freeing the chain handed the device's descriptors and
        // bounce buffer to the next caller while it was still reading them.
        //
        // Asserted as "the device never heard about it", not as "the counts
        // came back", because the old code restored the counts too -- after
        // the notify.
        ready();
        let free_before = { DEVICE.lock().as_ref().unwrap().queue.free_count() };
        let completions_before = completions();
        let faults_before = device_faults();

        // Hold every timer slot, so the reservation must fail.
        let mut held = alloc::vec![];
        while let Ok(sleep) = crate::task::try_sleep_ticks(1_000_000) {
            held.push(sleep);
        }
        assert_eq!(crate::task::free_timer_slots_for_test(), 0, "the timer table did not fill");

        let mut buf = [0u8; SECTOR_BYTES];
        assert_eq!(
            block_on(read_at(1, &mut buf)),
            Err(BlockError::QueueFull),
            "a request with no deadline available was accepted"
        );
        assert_eq!(
            { DEVICE.lock().as_ref().unwrap().queue.free_count() },
            free_before,
            "the refused request left descriptors allocated"
        );
        drop(held);

        // Nothing was published, so nothing can complete. A completion here
        // would be the device acting on a chain the driver had taken back.
        let mut budget = 5_000_000u64;
        while budget > 0 {
            core::hint::spin_loop();
            budget -= 1;
        }
        assert_eq!(
            completions(),
            completions_before,
            "the device completed a request the driver refused, so it had been notified"
        );
        assert_eq!(device_faults(), faults_before, "the refusal produced a device fault");
    }

    #[test_case]
    fn a_timed_out_request_keeps_its_chain_until_the_device_gives_it_back() {
        // The device owns a chain until it completes it, and a deadline says
        // nothing about the device. Freeing on timeout hands the descriptors
        // and the bounce buffer to the next request, and the late completion
        // then marks *that* request done from a status byte written for this
        // one: a wrong answer reported as success.
        //
        // `finish` is called directly with the timeout status rather than by
        // waiting out five seconds of ticks, because the property under test is
        // what the driver does with the verdict, not how long it takes to reach
        // it. The request itself is real and the device does complete it, which
        // is what makes the reclaim half observable.
        ready();
        let free_before = { DEVICE.lock().as_ref().unwrap().queue.free_count() };
        let abandoned_before = abandoned();
        let reclaimed_before = reclaimed();

        let head = submit(0, SECTOR_BYTES, None).expect("the queue refused a lone request");
        assert_eq!(
            finish(head, STATUS_TIMED_OUT, None),
            Err(BlockError::Timeout),
            "a timed-out request did not report a timeout"
        );
        assert_eq!(abandoned(), abandoned_before + 1, "the timeout was not recorded");
        assert!(
            { DEVICE.lock().as_ref().unwrap().queue.free_count() } < free_before,
            "the chain was freed while the device still owned it"
        );

        // The device completes it regardless; the handler is what reclaims it.
        let mut budget = 200_000_000u64;
        while reclaimed() == reclaimed_before && budget > 0 {
            core::hint::spin_loop();
            budget -= 1;
        }
        assert_eq!(
            reclaimed(),
            reclaimed_before + 1,
            "the completion never reclaimed the quarantined chain, so it is leaked"
        );
        assert_eq!(
            { DEVICE.lock().as_ref().unwrap().queue.free_count() },
            free_before,
            "the reclaimed chain was not returned to the free list"
        );
    }

    #[test_case]
    fn a_request_past_the_end_of_the_disk_is_reported_as_a_device_error() {
        // The device's verdict, which nothing else here exercises: every other
        // request in this module asks for a sector that exists, so `finish`'s
        // error arm and the status byte it reads have never run. A status read
        // that returned a constant zero would pass every other test in the
        // file.
        //
        // The disk is 2048 sectors; virtio-blk answers a read past the end with
        // an I/O error rather than truncating.
        ready();
        let mut buf = [0u8; SECTOR_BYTES];
        let verdict = block_on(read_at(DISK_SECTORS, &mut buf));
        assert_eq!(
            verdict,
            Err(BlockError::Device(BlkStatus::IoError)),
            "a read past the end of the disk was not reported as a device error"
        );
        // The chain comes back even when the device refuses the request. An
        // error path that leaks descriptors drains the queue silently, and the
        // symptom appears in code with nothing to do with the cause.
        let free = { DEVICE.lock().as_ref().unwrap().queue.free_count() };
        assert_eq!(free, QUEUE_SIZE, "a failed request leaked its chain");
        // And one error does not wedge the device.
        block_on(read_at(1, &mut buf)).expect("the device was unusable after one error");
        assert_eq!(u64::from_le_bytes(buf[0..8].try_into().unwrap()), 1);
    }

    #[test_case]
    fn a_full_queue_refuses_a_request_rather_than_reusing_a_live_descriptor() {
        // Forced rather than raced: 21 concurrent requests would be a statement
        // about scheduling, and CLAUDE.md rules that out as coverage. Draining
        // the free list directly makes the refusal deterministic.
        ready();
        let held = {
            let mut guard = DEVICE.lock();
            let q = &mut guard.as_mut().unwrap().queue;
            let mut heads = alloc::vec![];
            while let Some(h) = q.alloc_chain(3) {
                heads.push(h);
            }
            heads
        };
        let mut buf = [0u8; SECTOR_BYTES];
        assert_eq!(
            block_on(read_at(1, &mut buf)),
            Err(BlockError::QueueFull),
            "a full queue accepted a request, which reuses a descriptor the device is reading"
        );
        {
            let mut guard = DEVICE.lock();
            let q = &mut guard.as_mut().unwrap().queue;
            for h in held {
                q.free_chain(h);
            }
        }
        // The refusal must be a refusal, not a wedge: a leaked in-flight marker
        // would leave the driver unable to submit anything afterwards.
        block_on(read_at(1, &mut buf)).expect("the driver did not recover from a full queue");
        assert_eq!(u64::from_le_bytes(buf[0..8].try_into().unwrap()), 1);
    }

    #[test_case]
    fn every_descriptor_is_returned_after_a_request_completes() {
        // A chain leaked per request drains the queue after 21 of them, and the
        // symptom is `QueueFull` in code that has nothing to do with the leak.
        ready();
        // Absolute, not a delta. A leak in an *earlier* test lowers the
        // baseline, and a before/after comparison then passes on a queue that
        // is already draining -- which is the failure this test exists to
        // catch, one test too late.
        let free_before = { DEVICE.lock().as_ref().unwrap().queue.free_count() };
        assert_eq!(
            free_before, QUEUE_SIZE,
            "the queue entered this test with {free_before} of {QUEUE_SIZE} descriptors free; \
             an earlier request leaked a chain"
        );
        let mut buf = [0u8; SECTOR_BYTES];
        for lba in 0..8u64 {
            block_on(read_at(lba, &mut buf)).expect("the read failed");
            assert_eq!(u64::from_le_bytes(buf[0..8].try_into().unwrap()), lba);
        }
        let free_after = { DEVICE.lock().as_ref().unwrap().queue.free_count() };
        assert_eq!(free_after, free_before, "requests leaked descriptors");
    }
}
